apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-vdjqchzg
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-vdjqchzg:019daeed4527f89b28d2f1f21d1f9aeafc5bc50f@sha256:d9a2ec9a7e50ff83a8b78aa4d2f25ec93b1d85efac5935f80df3fe39560c15be
          name: container-image
